name: Integration Tests
on:
  pull_request:
    paths:
      - "**/*.go"
      - "**/*.bats"
      - ".github/workflows/pr.yml"
      - "go.mod"

jobs:
  integration:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24

    steps:
      - uses: actions/checkout@v7

      - name: Install BATS
        run: |
          apt-get update
          apt-get install -y bats

      - name: Build forte
        run: make build
        env:
          GOFLAGS: -buildvcs=false

      - name: Run integration tests
        run: bats -r ./integration_tests
