name: Quality Checks
on:
  push:
    paths:
      - "**/*.go"
      - "go.mod"
      - ".github/workflows/push.yml"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Build
        run: make build

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Unit Tests
        run: make test

  examples:
    name: Example Deployments
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: PHP App Deployment
        run: make -s example-php-deployment
